### ISSUE TITLE
Compatibility Inquiry: sys-proctable (1.3.0)  with Ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [djberg96/sys-proctable#109]
Hi,

I'm seeking confirmation regarding the compatibility of the sys-proctable (1.3.0)  with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on https://github.com/djberg96/sys-proctable/blob/main/.github/workflows/ruby.yml, ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2', 'jruby', 'truffleruby'] Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by djberg96** [comment]
I've added 3.3 to the matrix. It's green. Enjoy!
