### ISSUE TITLE
Adding support for listing process threads

### ISSUE THREAD

**Issue by rmc3** [djberg96/sys-proctable#39]
It could be useful to have this library support fetching information about process threads (i.e., ```/proc/<pid>/tasks/*``` on *nix systems, compare to the ```-L``` flag in ```ps```). It's possible that this is already supported and I'm just missing it in the documentation.

**Comment by djberg96** [comment]
On some platforms it may be part of the underlying struct already, but I'm not sure about Linux. I'll double check.

**Comment by rmc3** [comment]
For my purposes (at least), adding a thread count value to the Linux struct might be enough, similar to what currently exists for the Windows (:thread_count) and AIX (:nlwp) structs. It doesn't seem like it'd be terribly difficult to implement, something along the lines of ```Dir.glob("/proc/#{pid}/task/*").length

Of course, more in-depth thread information would be nice too. Does ```Sys::ProcTable.ps()``` currently return all threads by default on AIX? My initial reading of the code makes me think it does.

**Comment by djberg96** [comment]
I'm not sure about AIX. It was contributed code, so I've no way to check. Anyway, go ahead and send me a PR if you like and I'll take a look. Be sure to handle cases where it's unreadable for whatever reason.
