### ISSUE TITLE
New Gem release

### ISSUE THREAD

**Issue by rmc3** [djberg96/sys-proctable#41]
After the merge of #40, it could be useful to have a new version of the gem containing that change set available on RubyGems.

EDIT: I suppose only the Linux platform would strictly need to be updated, as that's the only platform which was affected by #40

**Comment by djberg96** [comment]
Well, it's all bundled together. I don't do separate releases for separate platforms. It takes me about an hour to do it all for this particular gem, so it may be a few days, but I'll get to it.

**Comment by rmc3** [comment]
Understood. Thanks, @djberg96!

**Comment by rmc3** [comment]
Just want to note that this blocks https://github.com/sensu-plugins/sensu-plugins-process-checks/issues/3

Thanks!

**Comment by djberg96** [comment]
sys-proctable 0.9.6 released.

**Comment by rmc3** [comment]
Greatly appreciated, @djberg96 !
