### ISSUE TITLE
FreeBSD: Unable to resolve types vm_size_t and lwpid_t

### ISSUE THREAD

**Issue by mikeowens** [djberg96/sys-proctable#42]
These trigger and exception with ffi-1.9.8 on FreeBSD 10.

**Comment by djberg96** [comment]
Ok, I use uint32_t and pid_t now. Can you please checkout the latest and run the tests to verify?

**Comment by mikeowens** [comment]
Works great. Thanks.

**Comment by djberg96** [comment]
You're welcome! I still want to add some tests, and do some 32v64 testing yet, but this should be ready by the next release.
