### ISSUE TITLE
>= 0.9.5 fails to retrieve ps on Mac

### ISSUE THREAD

**Issue by dueckes** [djberg96/sys-proctable#44]
Upgrading to 0.9.5 or beyond fails to retrieve a process list on a Mac.
Example output:
```
machine$ bundle install
... 
Using sys-proctable 0.9.6
Using bundler 1.9.1
...
machine$ bundle exec irb
2.2.1 :001 > require 'sys/proctable'
 => true
2.2.1 :002 > ::Sys::ProcTable.ps
ArgumentError: NULL pointer given
	from (irb):2:in `ps'
	from (irb):2
	from /Users/matthew.ueckerman/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```
Tested on Ruby 2.1.2 and 2.2.1

**Comment by djberg96** [comment]
What's the output of uname -a?

**Comment by djberg96** [comment]
Also, if you can narrow down the specific process that would help me debug.

**Comment by dueckes** [comment]
Mac OSX 10.10.2
uname -a:
```
<omitted> 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
```

Not sure narrowing down on the specific process is applicable - the scenario mentioned requests the complete process table.

**Comment by djberg96** [comment]
Try this:

    Sys::ProcTable.ps{ |pt| p pt.pid }

This should give you an idea of which process is actually causing the error. Then use the command line "ps" command and grep on the suspected pid that's causing the issue, and send me the details of that process if you can.

**Comment by astlock** [comment]
```
uname -a
Darwin anton-mbair.lan 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
```
```
irb(main):024:0> Sys::ProcTable.ps{ |pt| p pt.pid }
43494
43493
43491
43490
43460
43457
43456
43455
43454
43452
43425
43338
43337
43252
43186
43183
43182
43180
43130
43127
43126
43125
43118
43114
43095
43093
43092
43091
43090
43089
43087
43086
43084
43083
43081
43080
43079
43078
43070
43066
43065
43064
43063
43062
43061
43060
43059
43058
43057
ArgumentError: NULL pointer given
	from (irb):24:in `ps'
	from (irb):24
	from /usr/bin/irb:12:in `<main>'
```
```
ps auxw | grep 43057
anton          43057   0.0  0.2  2528152  14576   ??  S    11:16PM   0:00.61 /System/Library/PrivateFrameworks/MessagesKit.framework/Resources/soagent.app/Contents/MacOS/soagent
ps auxw | grep 43058
anton          43058   0.0  0.1  2492504   5716   ??  S    11:16PM   0:00.16 /usr/libexec/secinitd
ps auxw | grep 43059
anton          43059   0.0  0.1  2501028   6188   ??  S    11:16PM   0:00.25 /System/Library/PrivateFrameworks/TCC.framework/Resources/tccd
```
Will it help?

**Comment by djberg96** [comment]
Can you tell the details of the next process? Which I'm guessing is 43056 in this case.

**Comment by astlock** [comment]
ok, repeat the experiment
```
irb(main):010:0* Sys::ProcTable.ps{ |pt| p pt.pid }
78324
78323
78322
78310
78293
78274
ArgumentError: NULL pointer given
	from (irb):10:in `ps'
	from (irb):10
	from /usr/bin/irb:12:in `<main>'
irb(main):011:0>
```
![366d555w](https://cloud.githubusercontent.com/assets/988910/6905719/b368aa58-d732-11e4-81bd-13affec37b2e.png)

```
anton           78272   0.0  1.5  3721576 128040   ??  Ss   11:00PM   0:03.92 /System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc/Contents/MacOS/com.apple.WebKit.WebContent
```

**Comment by djberg96** [comment]
Hm, something interesting going on with 78272 there. Looks like the process name....has comma separated values? Am I seeing the full process name?

**Comment by astlock** [comment]
yes, it was the full process name. Here is another example of such process:
![6jr0zxo6](https://cloud.githubusercontent.com/assets/988910/6917986/7c8c48a2-d7b2-11e4-9ad9-043a7794b772.png)

```
anton           79031   0.0  1.9  3749916 159332   ??  Ss    1:36PM   0:06.58 /System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc/Contents/MacOS/com.apple.WebKit.WebContent
```
Also, I noticed that the problem is reproducible always when Safari is running.

**Comment by djberg96** [comment]
Yep, I'm seeing the same thing, thanks. I'm seeing some bizarre behavior in general....let me try to narrow this down.

**Comment by djberg96** [comment]
Ok, it's definitely an issue in the argv_of_pid internal function. Looking at it.

**Comment by djberg96** [comment]
I've narrowed it down to the "while (cp[0])" block, as there's an unexpected null. I need to review this code block.

**Comment by djberg96** [comment]
Ok, fixed. You can use the latest in the repo or wait for the next release. I'll try to get it out this weekend.

**Comment by jamesfzhang** [comment]
Hi Daniel, I'm running into the same problem on 0.9.6.

`Darwin HOVA.local 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64`

![screen shot 2015-04-18 at 4 43 28 pm](https://cloud.githubusercontent.com/assets/2057670/7217227/35e1ebfa-e5ea-11e4-9fb6-ccb75a2ebcb8.png)

**Comment by djberg96** [comment]
Yep, it's fixed in 0.9.7, which I haven't released yet. I'l try to do that today.

**Comment by jamesfzhang** [comment]
@djberg96 Thanks!

**Comment by benbalter** [comment]
I'm receiving the same error in `0.9.9`. Even after a restart, it consistently fails on PID `45`, which is `UserEventAgent`. `uname -a` results in:

> `Darwin Bens-MacBook-Air.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64`

**Comment by djberg96** [comment]
@benbalter, I cannot duplicate with 0.9.9. For me it was 44 (system) and 292 (aqua), and both worked fine.

**Comment by benbalter** [comment]
I can reproduce it consistently with the following:

```irb
be irb
[1] pry(main)> require 'sys/proctable'
=> true
[2] pry(main)> include Sys
=> Object
[3] pry(main)> Sys::ProcTable.ps{ |pt| p pt.pid }
35403
35324
35239
33444
33442
33389
33388
33372
33371
33370
33369
30234
30232
24727
24724
24674
24640
24608
24607
24606
24603
24586
24585
24582
24528
24465
24421
24397
24396
24260
24259
24229
24211
24193
24066
23757
23741
23516
23389
17118
8664
6770
5198
4862
2596
2595
2594
2213
1687
1600
1599
1238
1230
1227
1182
1167
1166
1165
1095
1093
1090
1088
1000
891
874
872
870
730
710
709
686
677
649
602
601
599
598
597
596
595
550
549
547
546
545
544
543
542
541
540
539
538
537
536
535
534
533
532
531
529
527
526
495
477
476
475
474
473
472
471
470
469
468
466
465
464
463
461
457
456
453
452
451
450
449
448
441
440
437
426
425
424
423
422
412
411
410
409
403
402
401
398
397
396
395
393
392
391
390
389
387
386
385
379
373
370
368
366
365
363
362
361
360
359
357
356
354
353
351
350
347
344
342
340
339
338
337
336
335
334
333
331
330
329
328
326
325
323
322
321
318
317
314
311
310
309
307
306
304
302
300
292
284
256
250
249
247
246
245
243
242
241
240
237
234
231
217
208
205
203
201
198
196
195
193
190
189
167
164
159
152
141
138
137
136
134
133
127
109
106
105
104
102
101
100
99
96
92
91
90
87
85
84
83
81
79
78
77
75
74
72
71
70
66
65
62
55
54
53
48
47
ArgumentError: NULL pointer given
from (pry):3:in `ps'
[4] pry(main)> Sys::ProcTable::VERSION
=> "0.9.9"
```

**Comment by djberg96** [comment]
@benbalter Is there anything special about your environment? Can you paste the output of ps -ef | grep UserEventAgent? Also, you can just do ProcTable.ps(45) to get at just the one you're interested in.

**Comment by benbalter** [comment]
>  Is there anything special about your environment?

Not that I can think of (MacBook Air that is ~1 month old). Set up with https://github.com/mikemcquaid/strap. Suspected Ruby 2.3.0 was the culprit, but downgrading to 2.2.3 didn't resolve the issue.

> Can you paste the output of ps -ef | grep UserEventAgent?

```
➜  sys-proctable-test git:(master) ✗  ps -ef | grep UserEventAgent
  501   300     1   0  8:14PM ??         0:01.77 /usr/libexec/UserEventAgent (Aqua)
    0    45     1   0  8:14PM ??         0:06.04 /usr/libexec/UserEventAgent (System)
  501 78924  1230   0 12:08PM ttys001    0:00.00 grep --color UserEventAgent
```

(Not sure what's going on with the two versions there).

>  Also, you can just do ProcTable.ps(45) to get at just the one you're interested in.

Same error. `ArgumentError: NULL pointer given`

**Comment by djberg96** [comment]
@benbalter I don't have a clue. I'm running the same kernel as you. Does ProcTable.ps(300) work? Also, what's the output if you run the locale command?

**Comment by benbalter** [comment]
>  Does ProcTable.ps(300) work?

\*scratches head\* Works just fine.

> Also, what's the output if you run the locale command?

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by djberg96** [comment]
@benbalter well, i'm afraid this is going to require you to grab the source and tinker with the argv_of_pid function. The relevant commit for the previous fix is https://github.com/djberg96/sys-proctable/commit/4505b4335a1a3481523df2875153c0b3b36f226e.
