### ISSUE TITLE
rss on linux is different from that reported by `top` and `ps`

### ISSUE THREAD

**Issue by jf** [djberg96/sys-proctable#50]
(This is on Ubuntu 14.04, although I suspect that it's more an OS thing than a distro thing; `uname -r` = 3.13.0-86-generic)

The values of rss as reported by `top` and `ps` agree; but `ProcTable.ps` gives a drastically reduced number. Why is that? As an example:

```
# ps -eo pid,rss,comm |grep ntp
 1888  1960 ntpd

irb> ProcTable.ps.select {|p| p.comm =~ /ntp/ }.map {|ps| [ps.pid, ps.rss]}
=> [[1888, 490]]
```

**Comment by djberg96** [comment]
@jf The rss value that sys-proctable retrieves is what's stored in /proc. That value actually refers to *pages*. What top and ps are showing you is actually `rss_value * sysconf(_SC_PAGESIZE) `, which is (almost) always 4 in practice. Hence, the value you see from `top` and `ps` is four times larger than what you see from sys-proctable.

http://man7.org/linux/man-pages/man5/proc.5.html

**Comment by jf** [comment]
I see. Thanks for the education (and much appreciated at that)! Technically speaking though (just tried it), `sysconf(_SC_PAGESIZE)` gives me 4096, though; but it looks like is correct in that this is 4 * "Kilobyte", and the `top` and `ps` values are in KB as well. Thanks!
