### ISSUE TITLE
TypeError: unable to resolve type 'uint32_t'

### ISSUE THREAD

**Issue by ryanharnwell** [djberg96/sys-proctable#57]
Unable to load the gem on osx 10.9.5

11:47:44-ryan-~/apps/ (master *)$ gem list
*** LOCAL GEMS ***
...
...
sys-proctable (1.1.3 universal-darwin)

---------------------------------------------

irb(main):004:0> require 'sys/proctable'
TypeError: unable to resolve type 'uint32_t'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/ffi-1.9.3/lib/ffi/types.rb:70:in `find_type'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/ffi-1.9.3/lib/ffi/library.rb:496:in `find_type'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/ffi-1.9.3/lib/ffi/struct.rb:326:in `find_type'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/ffi-1.9.3/lib/ffi/struct.rb:320:in `find_field_type'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/ffi-1.9.3/lib/ffi/struct.rb:362:in `array_layout'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/ffi-1.9.3/lib/ffi/struct.rb:272:in `layout'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sys-proctable-1.1.3-universal-darwin/lib/darwin/sys/proctable.rb:30:in `<class:ProcBsdInfo>'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sys-proctable-1.1.3-universal-darwin/lib/darwin/sys/proctable.rb:29:in `<class:ProcTable>'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sys-proctable-1.1.3-universal-darwin/lib/darwin/sys/proctable.rb:5:in `<module:Sys>'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sys-proctable-1.1.3-universal-darwin/lib/darwin/sys/proctable.rb:4:in `<top (required)>'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Users/ryan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from (irb):4
	from /Users/ryan/.rbenv/versions/2.1.3/bin/irb:11:in `<main>'

**Comment by djberg96** [comment]
I think this was fixed in a more recent version of ffi. Can you update to the latest version of ffi and try again?

**Comment by djberg96** [comment]
@ryanharnwell Any luck?

**Comment by Umofomia** [comment]
FWIW, just noting here that I ran into the same issue and updating ffi (version 1.9.25 as of the time I tried it) indeed solved it.
