### ISSUE TITLE
Can't create processtable, OSX Sierra

### ISSUE THREAD

**Issue by pmck91** [djberg96/sys-proctable#58]
`No such file or directory @ dir_initialize - /proc (Errno::ENOENT)`

thrown from the following: 

`ProcTable.ps do |p|
      Process.kill("TERM", p.pid) if p.cmdline.include? "appium"
    end`

working on one osx machine and not on another.

**Comment by djberg96** [comment]
@pmck91 Can you please confirm the version of sys-proctable that you're using on the failing machine? Also, the output of `gem env` might be helpful.

As of 10.7, I don't access proc directly, but the underlying C functions probably do. Is it possible that /proc isn't mounted? That seems unlikely on OS X, though.

**Comment by djberg96** [comment]
@pmck91 Any word?

**Comment by djberg96** [comment]
No response, closing.
