### ISSUE TITLE
Fail builds on jruby-9.1.16.0

### ISSUE THREAD

**Issue by kacperduras** [djberg96/sys-proctable#73]
Hi!
CI builds: [here](https://travis-ci.org/kacperduras/jekyll-w2m)
CI fail log: [here](https://travis-ci.org/kacperduras/jekyll-w2m/jobs/368748816)
Git repository: [here](https://github.com/kacperduras/jekyll-w2m)
Related gem: [here](https://github.com/benbalter/word-to-markdown)

Any ideas? I don't know, why only builds on JRuby are marked as failed :\

**Comment by kacperduras** [comment]
@djberg96 Thanks for fast response, but it isn't works :\

CI log: [here](https://travis-ci.org/kacperduras/jekyll-w2m/jobs/368783431)

**Comment by djberg96** [comment]
@kacperduras right, I don't know why that doesn't work.

**Comment by kacperduras** [comment]
I'll try to find a solution to this problem and let you know how something is fixed ;)
Thanks a lot!

**Comment by djberg96** [comment]
@kacperduras I can tell you that the tests pass locally. For now I think the easiest solution is to just remove JRuby from your test matrix unless you *really* need it.
