### ISSUE TITLE
Files for FreeBSD for version 1.2.1 does not exist

### ISSUE THREAD

**Issue by mfechner** [djberg96/sys-proctable#76]
The `sys-proctable-1.2.1-universal-freebsd.gem` does not exist.
It seems that with version 1.2 the generation of these files stopped working.

Thanks a lot.

**Comment by djberg96** [comment]
There are no more platform-specific gems. There is a single gem that contains the source for all platforms, and will load the appropriate file depending on which platform it's running on.
